name: Build TeenWolf Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Set up Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew wrapper

      - name: Build the mod
        run: ./gradlew build

      - name: Upload compiled mod
        uses: actions/upload-artifact@v4
        with:
          name: TeenWolfMod
          path: build/libs/*.jar
